apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: horoanalytics-com-tls
spec:
  secretName: horoanalytics-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: horoanalytics.com
  dnsNames:
    - horoanalytics.com
    - www.horoanalytics.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - horoanalytics.com
          - www.horoanalytics.com
